export interface PlacedStudent {
  id: string;
  name: string;
  salary: string;
  monthlySalaryNumber: number;
  company: string;
  location: string;
  role: string;
  course: string;
  image: any;
  webImageUrl: string;
  badge?: string;
}

export const PLACED_STUDENTS: PlacedStudent[] = [
  {
    id: 'p-ravindra',
    name: 'Ravindra Prasad',
    salary: '₹30,000/month',
    monthlySalaryNumber: 30000,
    company: 'Staffing Pvt. Ltd',
    location: 'Andhra Pradesh',
    role: 'Lead Safety Officer',
    course: 'ADIS - Industrial Safety',
    image: require('../../assets/placements/ravindra_prasad.jpg'),
    webImageUrl: '/placements/ravindra_prasad.jpg',
    badge: '⭐ Highest Package',
  },
  {
    id: 'p-ankit',
    name: 'Ankit Kr Yadav',
    salary: '₹18,000/month',
    monthlySalaryNumber: 18000,
    company: 'Solar Plant',
    location: 'Maharashtra',
    role: 'Solar EHS Supervisor',
    course: 'PG Diploma in Industrial Safety',
    image: require('../../assets/placements/ankit_kr_yadav.jpg'),
    webImageUrl: '/placements/ankit_kr_yadav.jpg',
    badge: 'Clean Energy',
  },
  {
    id: 'p-vickey',
    name: 'Vickey Kr Verma',
    salary: '₹16,000/month',
    monthlySalaryNumber: 16000,
    company: 'Green stone Pvt. Ltd',
    location: 'Bangalore',
    role: 'Site Safety Inspector',
    course: 'Diploma in Fire & Safety (DFIS)',
    image: require('../../assets/placements/vickey_kr_verma.jpg'),
    webImageUrl: '/placements/vickey_kr_verma.jpg',
    badge: 'MNC Site',
  },
  {
    id: 'p-suraj',
    name: 'Suraj kr Pandit',
    salary: '₹18,000/month',
    monthlySalaryNumber: 18000,
    company: 'Solar Plant',
    location: 'Maharashtra',
    role: 'EHS Field Officer',
    course: 'Industrial Safety Management',
    image: require('../../assets/placements/suraj_kr_pandit.jpg'),
    webImageUrl: '/placements/suraj_kr_pandit.jpg',
    badge: 'Renewable Sector',
  },
  {
    id: 'p-suman',
    name: 'Suman Kumar',
    salary: '₹23,000/month',
    monthlySalaryNumber: 23000,
    company: 'Tata Power',
    location: 'Kalyan',
    role: 'Power Plant Safety Officer',
    course: 'Fire & Safety Engineering Lead',
    image: require('../../assets/placements/suman_kumar.jpg'),
    webImageUrl: '/placements/suman_kumar.jpg',
    badge: '🏆 Tata Group',
  },
  {
    id: 'p-rakesh',
    name: 'Rakesh Rajak',
    salary: '₹20,000/month',
    monthlySalaryNumber: 20000,
    company: 'EPI Gral',
    location: 'Gujarat',
    role: 'Industrial EHS Executive',
    course: 'ADIS Safety Certification',
    image: require('../../assets/placements/rakesh_rajak.jpg'),
    webImageUrl: '/placements/rakesh_rajak.jpg',
    badge: 'Heavy Industry',
  },
  {
    id: 'p-kaushal',
    name: 'Kaushal kr Yadav',
    salary: '₹24,000/month',
    monthlySalaryNumber: 24000,
    company: 'Tata Motors',
    location: 'Ahemdabad',
    role: 'Automobile Plant Safety Officer',
    course: 'Industrial Health & Safety',
    image: require('../../assets/placements/kaushal_kr_yadav.jpg'),
    webImageUrl: '/placements/kaushal_kr_yadav.jpg',
    badge: '🏆 Tata Motors',
  },
  {
    id: 'p-arjun',
    name: 'Arjun Singh',
    salary: '₹20,000/month',
    monthlySalaryNumber: 20000,
    company: 'Kirby Pvt. Ltd',
    location: 'Gujarat',
    role: 'PEB Safety Specialist',
    course: 'Diploma in Industrial Safety',
    image: require('../../assets/placements/arjun_singh.jpg'),
    webImageUrl: '/placements/arjun_singh.jpg',
    badge: 'Engineering Lead',
  },
  {
    id: 'p-anwar',
    name: 'Anwar Ali',
    salary: '₹18,000/month',
    monthlySalaryNumber: 18000,
    company: 'Torrent Pvt. Ltd',
    location: 'Muradabad',
    role: 'Process Safety Officer',
    course: 'Fire Prevention & Safety',
    image: require('../../assets/placements/anwar_ali.jpg'),
    webImageUrl: '/placements/anwar_ali.jpg',
    badge: 'Power & Utility',
  },
  {
    id: 'p-vicky',
    name: 'Vicky Kr Yadav',
    salary: '₹24,000/month',
    monthlySalaryNumber: 24000,
    company: 'Ravi Construction',
    location: 'Surat',
    role: 'Construction Safety Officer',
    course: 'Advance Diploma in Industrial Safety',
    image: require('../../assets/placements/vicky_kr_yadav.jpg'),
    webImageUrl: '/placements/vicky_kr_yadav.jpg',
    badge: 'Infrastructure',
  },
];
